In [3]:
import pandas as pd

In [4]:
#df es data frame
df = pd.read_csv('imdb_top_1000.csv')

In [5]:
print(df['Star1'])

0            Tim Robbins
1          Marlon Brando
2         Christian Bale
3              Al Pacino
4            Henry Fonda
             ...
995       Audrey Hepburn
996     Elizabeth Taylor
997       Burt Lancaster
998    Tallulah Bankhead
999         Robert Donat
Name: Star1, Length: 1000, dtype: object

In [8]:
df[df.Released_Year=='2000']

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
39,https://m.media-amazon.com/images/M/MV5BMDliMm...,Gladiator,2000,UA,155 min,"Action, Adventure, Drama",8.5,A former Roman General sets out to exact venge...,67.0,Ridley Scott,Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,1341460,"187,705,427"
69,https://m.media-amazon.com/images/M/MV5BZTcyNj...,Memento,2000,UA,113 min,"Mystery, Thriller",8.4,A man with short-term memory loss attempts to ...,80.0,Christopher Nolan,Guy Pearce,Carrie-Anne Moss,Joe Pantoliano,Mark Boone Junior,1125712,"25,544,867"
96,https://m.media-amazon.com/images/M/MV5BMTA2ND...,Snatch,2000,UA,104 min,"Comedy, Crime",8.3,"Unscrupulous boxing promoters, violent bookmak...",55.0,Guy Ritchie,Jason Statham,Brad Pitt,Benicio Del Toro,Dennis Farina,782001,"30,328,156"
97,https://m.media-amazon.com/images/M/MV5BOTdiNz...,Requiem for a Dream,2000,A,102 min,Drama,8.3,The drug-induced utopias of four Coney Island ...,68.0,Darren Aronofsky,Ellen Burstyn,Jared Leto,Jennifer Connelly,Marlon Wayans,766870,"3,635,482"
160,https://m.media-amazon.com/images/M/MV5BMGMzZj...,Hera Pheri,2000,U,156 min,"Action, Comedy, Crime",8.2,Three unemployed men look for answers to all t...,NaN,Priyadarshan,Akshay Kumar,Sunil Shetty,Paresh Rawal,Tabu,57057,NaN
244,https://m.media-amazon.com/images/M/MV5BMjQxMW...,Amores perros,2000,A,154 min,"Drama, Thriller",8.1,A horrific car accident connects three stories...,83.0,Alejandro G. Iñárritu,Emilio Echevarría,Gael García Bernal,Goya Toledo,Álvaro Guerrero,223741,"5,383,834"
253,https://m.media-amazon.com/images/M/MV5BYjZjOD...,Fa yeung nin wah,2000,U,98 min,"Drama, Romance",8.1,"Two neighbors, a woman and a man, form a stron...",85.0,Kar-Wai Wong,Tony Chiu-Wai Leung,Maggie Cheung,Ping Lam Siu,Tung Cho 'Joe' Cheung,124383,"2,734,044"
384,https://m.media-amazon.com/images/M/MV5BNDVkYW...,Dancer in the Dark,2000,U,140 min,"Crime, Drama, Musical",8.0,An East European girl travels to the United St...,61.0,Lars von Trier,Björk,Catherine Deneuve,David Morse,Peter Stormare,102285,"4,184,036"
512,https://m.media-amazon.com/images/M/MV5BMTYxMD...,Nueve reinas,2000,R,114 min,"Crime, Drama, Thriller",7.9,Two con artists try to swindle a stamp collect...,80.0,Fabián Bielinsky,Ricardo Darín,Gastón Pauls,Graciela Tenenbaum,María Mercedes Villagra,49721,"1,221,261"
514,https://m.media-amazon.com/images/M/MV5BMzY1Zj...,Almost Famous,2000,A,122 min,"Adventure, Comedy, Drama",7.9,A high-school boy is given the chance to write...,90.0,Cameron Crowe,Billy Crudup,Patrick Fugit,Kate Hudson,Frances McDormand,252586,"32,534,850"
641,https://m.media-amazon.com/images/M/MV5BMTI1ND...,Gongdong gyeongbi guyeok JSA,2000,NaN,110 min,"Action, Drama, Thriller",7.8,After a shooting incident at the North/South K...,58.0,Chan-wook Park,Lee Yeong-ae,Lee Byung-Hun,Kang-ho Song,Kim Tae-Woo,26518,NaN
644,https://m.media-amazon.com/images/M/MV5BYThkMz...,Remember the Titans,2000,U,113 min,"Biography, Drama, Sport",7.8,The true story of a newly appointed African-Am...,48.0,Boaz Yakin,Denzel Washington,Will Patton,Wood Harris,Ryan Hurst,198089,"115,654,751"
645,https://m.media-amazon.com/images/M/MV5BNDdhMz...,Wo hu cang long,2000,UA,120 min,"Action, Adventure, Fantasy",7.8,A young Chinese warrior steals a sword from a ...,94.0,Ang Lee,Yun-Fat Chow,Michelle Yeoh,Ziyi Zhang,Chen Chang,253228,"128,078,872"
647,https://m.media-amazon.com/images/M/MV5BN2Y5ZT...,Cast Away,2000,UA,143 min,"Adventure, Drama, Romance",7.8,A FedEx executive undergoes a physical and emo...,73.0,Robert Zemeckis,Tom Hanks,Helen Hunt,Paul Sanchez,Lari White,524235,"233,632,142"
793,https://m.media-amazon.com/images/M/MV5BNGY3NW...,Billy Elliot,2000,R,110 min,"Drama, Music",7.7,A talented young boy becomes torn between his ...,74.0,Stephen Daldry,Jamie Bell,Julie Walters,Jean Heywood,Jamie Draven,126770,"21,995,263"
796,https://m.media-amazon.com/images/M/MV5BNTIyNT...,Vampire Hunter D: Bloodlust,2000,U,103 min,"Animation, Action, Fantasy",7.7,"When a girl is abducted by a vampire, a legend...",62.0,Yoshiaki Kawajiri,Andrew Philpot,John Rafter Lee,Pamela Adlon,Wendee Lee,29210,"151,086"
797,https://m.media-amazon.com/images/M/MV5BMjZkOT...,"O Brother, Where Art Thou?",2000,U,107 min,"Adventure, Comedy, Crime",7.7,"In the deep south during the 1930s, three esca...",69.0,Joel Coen,Ethan Coen,George Clooney,John Turturro,Tim Blake Nelson,286742,"45,512,588"
944,https://m.media-amazon.com/images/M/MV5BMDc2MG...,Batoru rowaiaru,2000,NaN,114 min,"Action, Adventure, Drama",7.6,"In the future, the Japanese government capture...",81.0,Kinji Fukasaku,Tatsuya Fujiwara,Aki Maeda,Tarô Yamamoto,Takeshi Kitano,169091,NaN
953,https://m.media-amazon.com/images/M/MV5BZTM2ZG...,American Psycho,2000,A,101 min,"Comedy, Crime, Drama",7.6,A wealthy New York City investment banking exe...,64.0,Mary Harron,Christian Bale,Justin Theroux,Josh Lucas,Bill Sage,490062,"15,070,285"

In [7]:
df.Released_Year

0      1994
1      1972
2      2008
3      1974
4      1957
       ...
995    1961
996    1956
997    1953
998    1944
999    1935
Name: Released_Year, Length: 1000, dtype: object

In [14]:
df[(df.Released_Year == '2000') | (df.Released_Year =='2010')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
39,https://m.media-amazon.com/images/M/MV5BMDliMm...,Gladiator,2000,UA,155 min,"Action, Adventure, Drama",8.5,A former Roman General sets out to exact venge...,67.0,Ridley Scott,Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,1341460,"187,705,427"
69,https://m.media-amazon.com/images/M/MV5BZTcyNj...,Memento,2000,UA,113 min,"Mystery, Thriller",8.4,A man with short-term memory loss attempts to ...,80.0,Christopher Nolan,Guy Pearce,Carrie-Anne Moss,Joe Pantoliano,Mark Boone Junior,1125712,"25,544,867"
90,https://m.media-amazon.com/images/M/MV5BMWE3MG...,Incendies,2010,R,131 min,"Drama, Mystery, War",8.3,Twins journey to the Middle East to discover t...,80.0,Denis Villeneuve,Lubna Azabal,Mélissa Désormeaux-Poulin,Maxim Gaudette,Mustafa Kamel,150023,"6,857,096"
96,https://m.media-amazon.com/images/M/MV5BMTA2ND...,Snatch,2000,UA,104 min,"Comedy, Crime",8.3,"Unscrupulous boxing promoters, violent bookmak...",55.0,Guy Ritchie,Jason Statham,Brad Pitt,Benicio Del Toro,Dennis Farina,782001,"30,328,156"
97,https://m.media-amazon.com/images/M/MV5BOTdiNz...,Requiem for a Dream,2000,A,102 min,Drama,8.3,The drug-induced utopias of four Coney Island ...,68.0,Darren Aronofsky,Ellen Burstyn,Jared Leto,Jennifer Connelly,Marlon Wayans,766870,"3,635,482"
141,https://m.media-amazon.com/images/M/MV5BNzgxMz...,Udaan,2010,UA,134 min,Drama,8.2,"Expelled from his school, a 16-year old boy re...",NaN,Vikramaditya Motwane,Rajat Barmecha,Ronit Roy,Manjot Singh,Ram Kapoor,42341,"7,461"
145,https://m.media-amazon.com/images/M/MV5BYzhiND...,Shutter Island,2010,A,138 min,"Mystery, Thriller",8.2,"In 1954, a U.S. Marshal investigates the disap...",63.0,Martin Scorsese,Leonardo DiCaprio,Emily Mortimer,Mark Ruffalo,Ben Kingsley,1129894,"128,012,934"
151,https://m.media-amazon.com/images/M/MV5BMTgxOT...,Toy Story 3,2010,U,103 min,"Animation, Adventure, Comedy",8.2,The toys are mistakenly delivered to a day-car...,92.0,Lee Unkrich,Tom Hanks,Tim Allen,Joan Cusack,Ned Beatty,757032,"415,004,880"
160,https://m.media-amazon.com/images/M/MV5BMGMzZj...,Hera Pheri,2000,U,156 min,"Action, Comedy, Crime",8.2,Three unemployed men look for answers to all t...,NaN,Priyadarshan,Akshay Kumar,Sunil Shetty,Paresh Rawal,Tabu,57057,NaN
230,https://m.media-amazon.com/images/M/MV5BMjA5ND...,How to Train Your Dragon,2010,U,98 min,"Animation, Action, Adventure",8.1,A hapless young Viking who aspires to hunt dra...,75.0,Dean DeBlois,Chris Sanders,Jay Baruchel,Gerard Butler,Christopher Mintz-Plasse,666773,"217,581,231"
244,https://m.media-amazon.com/images/M/MV5BMjQxMW...,Amores perros,2000,A,154 min,"Drama, Thriller",8.1,A horrific car accident connects three stories...,83.0,Alejandro G. Iñárritu,Emilio Echevarría,Gael García Bernal,Goya Toledo,Álvaro Guerrero,223741,"5,383,834"
253,https://m.media-amazon.com/images/M/MV5BYjZjOD...,Fa yeung nin wah,2000,U,98 min,"Drama, Romance",8.1,"Two neighbors, a woman and a man, form a stron...",85.0,Kar-Wai Wong,Tony Chiu-Wai Leung,Maggie Cheung,Ping Lam Siu,Tung Cho 'Joe' Cheung,124383,"2,734,044"
345,https://m.media-amazon.com/images/M/MV5BMjEzMz...,Tropa de Elite 2: O Inimigo Agora é Outro,2010,NaN,115 min,"Action, Crime, Drama",8.0,"After a prison riot, former-Captain Nascimento...",71.0,José Padilha,Wagner Moura,Irandhir Santos,André Ramiro,Milhem Cortaz,79200,"100,119"
346,https://m.media-amazon.com/images/M/MV5BMzU5Mj...,The King's Speech,2010,U,118 min,"Biography, Drama, History",8.0,"The story of King George VI, his impromptu asc...",88.0,Tom Hooper,Colin Firth,Geoffrey Rush,Helena Bonham Carter,Derek Jacobi,639603,"138,797,449"
352,https://m.media-amazon.com/images/M/MV5BMTUyMT...,My Name Is Khan,2010,UA,165 min,Drama,8.0,An Indian Muslim man with Asperger's syndrome ...,50.0,Karan Johar,Shah Rukh Khan,Kajol,Sheetal Menon,Katie A. Keane,98575,"4,018,695"
355,https://m.media-amazon.com/images/M/MV5BNzY2Nz...,Black Swan,2010,A,108 min,"Drama, Thriller",8.0,A committed dancer struggles to maintain her s...,79.0,Darren Aronofsky,Natalie Portman,Mila Kunis,Vincent Cassel,Winona Ryder,699673,"106,954,678"
384,https://m.media-amazon.com/images/M/MV5BNDVkYW...,Dancer in the Dark,2000,U,140 min,"Crime, Drama, Musical",8.0,An East European girl travels to the United St...,61.0,Lars von Trier,Björk,Catherine Deneuve,David Morse,Peter Stormare,102285,"4,184,036"
512,https://m.media-amazon.com/images/M/MV5BMTYxMD...,Nueve reinas,2000,R,114 min,"Crime, Drama, Thriller",7.9,Two con artists try to swindle a stamp collect...,80.0,Fabián Bielinsky,Ricardo Darín,Gastón Pauls,Graciela Tenenbaum,María Mercedes Villagra,49721,"1,221,261"
514,https://m.media-amazon.com/images/M/MV5BMzY1Zj...,Almost Famous,2000,A,122 min,"Adventure, Comedy, Drama",7.9,A high-school boy is given the chance to write...,90.0,Cameron Crowe,Billy Crudup,Patrick Fugit,Kate Hudson,Frances McDormand,252586,"32,534,850"
601,https://m.media-amazon.com/images/M/MV5BYzM2OG...,Kokuhaku,2010,NaN,106 min,"Drama, Thriller",7.8,A psychological thriller of a grieving mother ...,NaN,Tetsuya Nakashima,Takako Matsu,Yoshino Kimura,Masaki Okada,Yukito Nishii,35713,NaN
602,https://m.media-amazon.com/images/M/MV5BZjRmNj...,Ang-ma-reul bo-at-da,2010,NaN,144 min,"Action, Crime, Drama",7.8,A secret agent exacts revenge on a serial kill...,67.0,Jee-woon Kim,Lee Byung-Hun,Choi Min-sik,Jeon Gook-Hwan,Ho-jin Chun,111252,"128,392"
605,https://m.media-amazon.com/images/M/MV5BMTgzMT...,Ajeossi,2010,R,119 min,"Action, Crime, Drama",7.8,A quiet pawnshop keeper with a violent past ta...,NaN,Jeong-beom Lee,Won Bin,Sae-ron Kim,Tae-hoon Kim,Hee-won Kim,62848,"6,460"
614,https://m.media-amazon.com/images/M/MV5BMTM0OD...,The Fighter,2010,UA,116 min,"Biography, Drama, Sport",7.8,"Based on the story of Micky Ward, a fledgling ...",79.0,David O. Russell,Mark Wahlberg,Christian Bale,Amy Adams,Melissa Leo,340584,"93,617,009"
641,https://m.media-amazon.com/images/M/MV5BMTI1ND...,Gongdong gyeongbi guyeok JSA,2000,NaN,110 min,"Action, Drama, Thriller",7.8,After a shooting incident at the North/South K...,58.0,Chan-wook Park,Lee Yeong-ae,Lee Byung-Hun,Kang-ho Song,Kim Tae-Woo,26518,NaN
644,https://m.media-amazon.com/images/M/MV5BYThkMz...,Remember the Titans,2000,U,113 min,"Biography, Drama, Sport",7.8,The true story of a newly appointed African-Am...,48.0,Boaz Yakin,Denzel Washington,Will Patton,Wood Harris,Ryan Hurst,198089,"115,654,751"
645,https://m.media-amazon.com/images/M/MV5BNDdhMz...,Wo hu cang long,2000,UA,120 min,"Action, Adventure, Fantasy",7.8,A young Chinese warrior steals a sword from a ...,94.0,Ang Lee,Yun-Fat Chow,Michelle Yeoh,Ziyi Zhang,Chen Chang,253228,"128,078,872"
647,https://m.media-amazon.com/images/M/MV5BN2Y5ZT...,Cast Away,2000,UA,143 min,"Adventure, Drama, Romance",7.8,A FedEx executive undergoes a physical and emo...,73.0,Robert Zemeckis,Tom Hanks,Helen Hunt,Paul Sanchez,Lari White,524235,"233,632,142"
748,https://m.media-amazon.com/images/M/MV5BOGUyZD...,The Social Network,2010,UA,120 min,"Biography, Drama",7.7,As Harvard student Mark Zuckerberg creates the...,95.0,David Fincher,Jesse Eisenberg,Andrew Garfield,Justin Timberlake,Rooney Mara,624982,"96,962,694"
755,https://m.media-amazon.com/images/M/MV5BMTQ2OT...,Harry Potter and the Deathly Hallows: Part 1,2010,A,146 min,"Adventure, Family, Fantasy",7.7,"As Harry, Ron, and Hermione race against time ...",65.0,David Yates,Daniel Radcliffe,Emma Watson,Rupert Grint,Bill Nighy,479120,"295,983,305"
760,https://m.media-amazon.com/images/M/MV5BMTU2Nj...,Flipped,2010,PG,90 min,"Comedy, Drama, Romance",7.7,Two eighth-graders start to have feelings for ...,45.0,Rob Reiner,Madeline Carroll,Callan McAuliffe,Rebecca De Mornay,Anthony Edwards,81446,"1,752,214"
771,https://m.media-amazon.com/images/M/MV5BMTAxND...,Tangled,2010,U,100 min,"Animation, Adventure, Comedy",7.7,The magically long-haired Rapunzel has spent h...,71.0,Nathan Greno,Byron Howard,Mandy Moore,Zachary Levi,Donna Murphy,405922,"200,821,936"
793,https://m.media-amazon.com/images/M/MV5BNGY3NW...,Billy Elliot,2000,R,110 min,"Drama, Music",7.7,A talented young boy becomes torn between his ...,74.0,Stephen Daldry,Jamie Bell,Julie Walters,Jean Heywood,Jamie Draven,126770,"21,995,263"
796,https://m.media-amazon.com/images/M/MV5BNTIyNT...,Vampire Hunter D: Bloodlust,2000,U,103 min,"Animation, Action, Fantasy",7.7,"When a girl is abducted by a vampire, a legend...",62.0,Yoshiaki Kawajiri,Andrew Philpot,John Rafter Lee,Pamela Adlon,Wendee Lee,29210,"151,086"
797,https://m.media-amazon.com/images/M/MV5BMjZkOT...,"O Brother, Where Art Thou?",2000,U,107 min,"Adventure, Comedy, Crime",7.7,"In the deep south during the 1930s, three esca...",69.0,Joel Coen,Ethan Coen,George Clooney,John Turturro,Tim Blake Nelson,286742,"45,512,588"
902,https://m.media-amazon.com/images/M/MV5BZDY3ZG...,Kari-gurashi no Arietti,2010,U,94 min,"Animation, Adventure, Family",7.6,The Clock family are four-inch-tall people who...,80.0,Hiromasa Yonebayashi,Amy Poehler,Mirai Shida,Ryûnosuke Kamiki,Tatsuya Fujiwara,80939,"19,202,743"
904,https://m.media-amazon.com/images/M/MV5BODhkZD...,True Grit,2010,PG-13,110 min,"Drama, Western",7.6,A stubborn teenager enlists the help of a toug...,80.0,Ethan Coen,Joel Coen,Jeff Bridges,Matt Damon,Hailee Steinfeld,311822,"171,243,005"
905,https://m.media-amazon.com/images/M/MV5BNDY2OT...,Hævnen,2010,R,118 min,"Drama, Romance",7.6,The lives of two Danish families cross each ot...,65.0,Susanne Bier,Mikael Persbrandt,Trine Dyrholm,Markus Rygaard,Wil Johnson,38491,"1,008,098"
906,https://m.media-amazon.com/images/M/MV5BMTY3Nj...,Despicable Me,2010,U,95 min,"Animation, Comedy, Crime",7.6,When a criminal mastermind uses a trio of orph...,72.0,Pierre Coffin,Chris Renaud,Steve Carell,Jason Segel,Russell Brand,500851,"251,513,985"
908,https://m.media-amazon.com/images/M/MV5BMTMzNz...,Kick-Ass,2010,UA,117 min,"Action, Comedy, Crime",7.6,Dave Lizewski is an unnoticed high school stud...,66.0,Matthew Vaughn,Aaron Taylor-Johnson,Nicolas Cage,Chloë Grace Moretz,Garrett M. Brown,524081,"48,071,303"
944,https://m.media-amazon.com/images/M/MV5BMDc2MG...,Batoru rowaiaru,2000,NaN,114 min,"Action, Adventure, Drama",7.6,"In the future, the Japanese government capture...",81.0,Kinji Fukasaku,Tatsuya Fujiwara,Aki Maeda,Tarô Yamamoto,Takeshi Kitano,169091,NaN
953,https://m.media-amazon.com/images/M/MV5BZTM2ZG...,American Psycho,2000,A,101 min,"Comedy, Crime, Drama",7.6,A wealthy New York City investment banking exe...,64.0,Mary Harron,Christian Bale,Justin Theroux,Josh Lucas,Bill Sage,490062,"15,070,285"

In [15]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [18]:
#Create a data base with dictionaries

dict = {'Name': ['John', 'Jane', 'Joe'],
       'Adress': ['123 Main St.', 'Birnery Ave.', 'UBC'],
       'Age': ['23', '15', '51']}
df1 = pd.DataFrame(dict)

In [19]:
df1

   Name        Adress Age
0  John  123 Main St.  23
1  Jane  Birnery Ave.  15
2   Joe           UBC  51

In [24]:
df1[df1.Name=='Jane']

   Name        Adress Age
1  Jane  Birnery Ave.  15

In [27]:
#Create a data base with lists

df2 = pd.DataFrame([[1,2,3,4], ['aa', 'bb', 'vv', 'cc'], [323, 135, 666, 222]])

In [28]:
df2

     0    1    2    3
0    1    2    3    4
1   aa   bb   vv   cc
2  323  135  666  222

In [30]:
#Create a data base with lists

df3 = pd.DataFrame([[1,2,3,4], ['aa', 'bb', 'vv', 'cc'], [323, 135, 666, 222]], columns=['a', 'b2', 'cc', 'dd'])

In [31]:
df3

     a   b2   cc   dd
0    1    2    3    4
1   aa   bb   vv   cc
2  323  135  666  222